title: Rosemary Nnaoama
logo: Rosemary.png
description: As a data analyst with over 3 years of experience, I excel at working with diverse data sources and transforming complex datasets into actionable insights to support informed decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
