title: Rosemary Nnaoma
logo: Rosemary.png
description: I am a Data Analyst and Business Intelligence professional with over 3 years of experience in the private and public sectors. I specialise in transforming complex data into clear and actionable insights that drive business decisions. With expertise in data visualisation, analytics tools, and business intelligence processes, I help organisations uncover stories hidden within their data, empowering them to make informed, strategic choices.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
